# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "@oyhpnayiaw"
description: >-
  oyhpnayiaw's blog
baseurl: ""
url: https://oyhpnayiaw.github.io
author:
  name: Wai Yan Phyo
  email: oyhpnayiaw@gmail.com
  handle: oyhpnayiaw
  url: https://oyhpnayiaw.github.io
  resume: https://docs.google.com/document/d/1EIFSyTvPf_ggfOfHiaphnn9Le33FDqktm47VlhHz9WE/edit?usp=sharing

permalink: /articles/:title
collections:
  works:
    output: true
    permalink: /works/:title
    sort_by: date
    reverse: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - package.json
  - pnpm-lock.yaml
  - create_tags.rb

sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
    values:
      image: /assets/default.png
  -
    scope:
      path: "_works"
    values:
      screenshots: ['1', '2', '3', '4']
  - 
    scope:
      path: "articles/tags" 
    values:
      layout: "tag"

paginate: 10
paginate_path: "/articles/page:num/"
