# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "@oyhpnayiaw"
description: >-
  oyhpnayiaw's blog
baseurl: ""
url: https://oyhpnayiaw.github.io
author:
  name: Wai Yan Phyo
  email: oyhpnayiaw@gmail.com
  handle: oyhpnayiaw
  url: https://oyhpnayiaw.github.io

permalink: /blog/:title
collections:
  projects:
    output: true
    permalink: /projects/:title
    sort_by: date
    reverse: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - package.json
  - pnpm-lock.yaml
  - create_tags.rb

sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
    values:
      image: /assets/favicon.ico # TODO: Change default site image
  - 
    scope:
      path: "blog/tags" 
    values:
      layout: "tag"

paginate: 10
paginate_path: "/blog/page:num/"
